#! /bin/sh

NAME=imagebuilder
DESC="Image loader server"

USER=imageloader
GROUP=imageloader

IL_PID="/var/run/$NAME.pid"
IL_PY="/usr/local/bin/ravello_image_loader_server.py"

AUTHBIND_COMMAND="/usr/bin/authbind --deep /usr/bin/python "

case "$1" in
        start)
                echo "Starting image server"
                touch "$IL_PID"
                chown $USER "$IL_PID"
                setcap cap_net_bind_service=+ep /usr/bin/python2.7
                start-stop-daemon --start -b -c "$USER" -g "$GROUP" -u "$USER" -x /usr/bin/python2.7 "$IL_PY" --pidfile "$IL_PID"
                #setcap cap_net_bind_service=-ep /usr/bin/python2.7
        ;;
        stop)
                echo "Stopping image server"
                #start-stop-daemon --stop --pidfile $IL_PID -u "$USER"
        ;;
esac

exit 0

