#!/usr/bin/env ruby

require 'dnsruby'
include Dnsruby

run_line = 'ssh '
res = Dnsruby::Resolver.new

ARGV.each do |arg|
  if arg =~ /(.*)@(.*)/
  	ip = res.query($2).answer[0].to_s.split(" ")[4]
  	run_line += "#{$1}@#{ip} "
  elsif
  	run_line += arg + " "
  end
end

system(run_line)